### PR TITLE
HIVE SCRIPT

### PR DESCRIPTION
**Pull request by aayush619**
Hive script to store the structured data in a table and then creating
dynamic partitions for different categories of products. A total of 11
partitions for 11 categories.

### CODE REVIEW

**Comment by rrish** [comment]
What are the names of the 11 categories? Also, for each category you are giving a bunch of key-value pairs with product names and their "review" which is an int right?

**Comment by aayush619** [comment]
Yea.. I have product name and the review count as an int. I've sent the
categories n all the products related to it to Simon. He'll share it wid u.

**Comment by aayush619** [comment]
PFA the category-product file.

On Wed, Apr 20, 2016 at 12:59 PM, Aayush Grover Aayush.Grover@colorado.edu
wrote:

> Yea.. I have product name and the review count as an int. I've sent the
> categories n all the products related to it to Simon. He'll share it wid u.
> On Apr 20, 2016 09:49, "rrish" notifications@github.com wrote:
> 
> > What are the names of the 11 categories? Also, for each category you are
> > giving a bunch of key-value pairs with product names and their "review"
> > which is an int right?
> > 
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub
> > https://github.com/CUBigDataClass/Team-Moonshot/pull/6#issuecomment-212485191

Alchoholic drinks
wine, beer, Vodka, whiskey, Rum, Tequila

Footwears:
sneakers, sports shoes, sandals, heels, boots, spike shoes

Accessories: 
aviator, wayfarer, digital watch, skeleton watch, analog watch, leather wallet

Electronics:
Dslr, tablet PC, playstation, 

Bags :  
laptop bag, RuckSack, Traveler bag, ] duffle bag, sling bag, shoulder bag.

Female Bags: 
bucket bag, clutch bag, hobo bag, fold over clutch, messenger bag, Minaudiere, Satchel, Wristlet

Skating & Skiing: 
SkateBoard, roller skates, hoverboard , electric scooter, surfing board

Cosmetics: 
Hairgel, hairspray, hairoil, bodyspray, showergel, shampoo, sunscreen, moisturizer, lipstick, lipgloss, eyeliner.

Drinks: 
Juice, tea, coffee

Milk: 
Whole milk, , flavored milk, lactose free milk, buttermilk. 

Chocs:
Cookie, Donut, pastry, cheesecake, pancake, icecream, chocolate.

**Comment by rrish** [comment]
Thanks

On Wednesday, April 20, 2016, aayush619 notifications@github.com wrote:

> PFA the category-product file.
> 
> On Wed, Apr 20, 2016 at 12:59 PM, Aayush Grover <
> Aayush.Grover@colorado.edu
> <javascript:_e(%7B%7D,'cvml','Aayush.Grover@colorado.edu');>>
> wrote:
> 
> > Yea.. I have product name and the review count as an int. I've sent the
> > categories n all the products related to it to Simon. He'll share it wid
> > u.
> > On Apr 20, 2016 09:49, "rrish" <notifications@github.com
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> > 
> > > What are the names of the 11 categories? Also, for each category you are
> > > giving a bunch of key-value pairs with product names and their "review"
> > > which is an int right?
> > > 
> > > —
> > > You are receiving this because you authored the thread.
> > > Reply to this email directly or view it on GitHub
> > > <
> > > https://github.com/CUBigDataClass/Team-Moonshot/pull/6#issuecomment-212485191
> 
> Alchoholic drinks
> wine, beer, Vodka, whiskey, Rum, Tequila
> 
> Footwears:
> sneakers, sports shoes, sandals, heels, boots, spike shoes
> 
> Accessories:
> aviator, wayfarer, digital watch, skeleton watch, analog watch, leather
> wallet
> 
> Electronics:
> Dslr, tablet PC, playstation,
> 
> Bags :
> laptop bag, RuckSack, Traveler bag, ] duffle bag, sling bag, shoulder bag.
> 
> Female Bags:
> bucket bag, clutch bag, hobo bag, fold over clutch, messenger bag,
> Minaudiere, Satchel, Wristlet
> 
> Skating & Skiing:
> SkateBoard, roller skates, hoverboard , electric scooter, surfing board
> 
> Cosmetics:
> Hairgel, hairspray, hairoil, bodyspray, showergel, shampoo, sunscreen,
> moisturizer, lipstick, lipgloss, eyeliner.
> 
> Drinks:
> Juice, tea, coffee
> 
> Milk:
> Whole milk, , flavored milk, lactose free milk, buttermilk.
> 
> Chocs:
> Cookie, Donut, pastry, cheesecake, pancake, icecream, chocolate.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/CUBigDataClass/Team-Moonshot/pull/6#issuecomment-212563288

## 

Rishabh Raghavendran
Graduate Student
ECEE Dept.

**Pull request merged**
